# Generated by Django 2.2.16 on 2021-04-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdata',
            name='date',
            field=models.CharField(blank=True, db_column='F_DATE', max_length=255, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='linkdata',
            name='id',
            field=models.AutoField(auto_created=True, db_column='F_LOG_ID', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='linkdata',
            name='uri',
            field=models.TextField(blank=True, db_column='F_URI', verbose_name='URI запроса'),
        ),
    ]
